# Generated by Django 4.2.8 on 2023-12-04 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_remove_reservation_person_reservation_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='room_booked',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.room'),
        ),
    ]
